getweather/urls.py
from django.urls import path

from . import views
from .views import RULView,AnomalyView

app_name = "getweather"

# urlpatterns = [
#     path("", views.IndexView.as_view(), name="index"),
#     path("<int:pk>/", views.DetailView.as_view(), name="detail"),
#     path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
#     path("<int:question_id>/vote/", views.vote, name="vote"),
# ]

urlpatterns = [
    path("show_weather_data/", views.show_weather_data, name="show_weather_data"),
    path("", views.solidification, name="solidification"), 
    path("solidificationAPI/", views.solidificationAPI, name="solidificationAPI"),
    path("rul/", RULView.as_view(), name="rul"),
    path("anomaly/", AnomalyView.as_view(), name="anomaly"),
]

wmodel/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", include("getweather.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

getweather/models.py
from django.db import models


class WeatherV1(models.Model):
    date_w= models.DateField(max_length=200)
    time_w=models.TimeField(max_length=200)
    temperature = models.FloatField()
    humidity = models.FloatField()
    precipitation = models.FloatField()
    windspeed = models.FloatField()
    solar_rad = models.FloatField()
    solar_engy = models.FloatField()
    delta_t = models.FloatField()
    place= models.CharField(max_length=200)
    zipcode=models.IntegerField()
    def __str__(self):
        header=f"Date of Input : {self.date_w} Time of Input : {self.time_w}"
        return header

class OutputV1(models.Model):
    remark_text = models.CharField(max_length=2000)
    avg_delta_t = models.    delta_t = models.FloatField()
    def __str__(self):
        return self.remark_text

getweather/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
from .models import WeatherV1, OutputV1
import requests
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from .utils import predict_generate_and_demand,message_Predict,predict_rul,detect_anomalies,predict_solidification

#Temp Storage
Data_Array=[]
DeltaT_Array=[]
GBModel_Array=[]
Sum_DeltaT=0.0
time_w=0
date_w=0



class RULView(generic.View):
    model = WeatherV1
    template_name = "getweather/rul.html"
    def get(self,requests):
        return render(requests,self.template_name);

    def post(self, request):
        # Retrieve data from the form
        input_data = {
        'temperature': [float(request.POST.get('temperature'))],
        'pressure': [float(request.POST.get('pressure'))],
        'flow_rate': [float(request.POST.get('flow_rate'))],
        'vibration': [float(request.POST.get('vibration'))],
        'motor_current': [float(request.POST.get('motor_current'))],
        'operating_hours': [float(request.POST.get('operating_hours'))]
    }
        
        result=predict_rul(input_data)
        result=str(result).strip()
        result=result if len(result)>0 else "NO RUL DETECTED"
        # print(result)
        # Pass the result back to the template
        return render(request, self.template_name, {'result': result})




class AnomalyView(generic.View):
    template_name = "getweather/anomaly.html"

    def get(self,requests):
        return render(requests,self.template_name);

    def post(self, request):
        # Retrieve data from the form
        input_data = {
        'CL_out_temp': float(request.POST.get('CL_out_temp')),
        'Fluid_temp_at_3V_in': float(request.POST.get('Fluid_temp_at_3V_in')),
        'HT_out_fluid_temp': float(request.POST.get('HT_out_fluid_temp')),
        'HE_fluid_in_temp': float(request.POST.get('HE_fluid_in_temp')),
        'HE_fluid_out_temp': float(request.POST.get('HE_fluid_out_temp')),
        'CT_in_Fluid_temp':float(request.POST.get('CT_in_Fluid_temp')),
        'CT_out_fluid_temp': float(request.POST.get('CT_out_fluid_temp')),
        'CL_in_fluid_temp': float(request.POST.get('CL_in_fluid_temp'))
    }
        # print(input_data['CL_in_fluid_temp'])
        result=detect_anomalies(input_data).strip()
        result=result if len(result)>0 else "NO ANOMALY DETECTED"

        # print(result)
        
        
        # Pass the result back to the template
        return render(request, self.template_name, {'result': result})


#Views

def solidification(request):
    result_dict = request.session.pop('result_dict', {})
    return render(request, "getweather/solidification.html",{'result_dict': result_dict})



#API FOR MESSAGE
def solidificationAPI(request):
    global Data_Array, DeltaT_Array, Sum_DeltaT, time_w, date_w, GBModel_Array
    Data_Array = []
    GBModel_Array=[]
    DeltaT_Array = []
    Sum_DeltaT = 0.0
    time_w = 0
    date_w = 0
   
    if request.method == "POST":
        time_w = request.POST.get('time_w')
        if time_w:
            time_o = time_w
            time_w = time_o[11:13]
            date_w = time_o[0:10]
            show_weather_data(date_w,time_w,144411)
            msg=""
            # for Message Framework
            if(Sum_DeltaT>0):
                msg=f"Everything Going Good ! , In Next 3 Hours There will an increase of {Sum_DeltaT} degree in Hot Tank Temperature.Hence, Solidification is NOT Possible"
            else:
                 # Store the dictionary in the session
                request.session['result_dict'] = message_Predict(GBModel_Array,Sum_DeltaT)
                msg=f"Solidification is Possible ! In Next 3 Hours from Time: {time_w}:00 and Date: {date_w} "

            if(Sum_DeltaT>0):
                messages.success(request, msg)
            else:
                messages.error(request, msg)
            # Redirect to a view where you want to display the messages
            return redirect(reverse("getweather:solidification"))
        else:
            messages.error(request, "Missing 'time_w' parameter.")
            # Redirect back to the form or some other view
            return redirect(reverse("getweather:solidification"))
    else:
        messages.error(request, "Only POST method is allowed.")
        # Redirect back to the form or some other view
        return redirect(reverse("getweather:solidification"))



# Leave the rest of the views (detail, results, vote) unchanged & CALC
def show_weather_data(date_w,time_w,pincode_w):
    global Sum_DeltaT
    global Data_Array
    global DeltaT_Array
    global GBModel_Array
    date=date_w
    pincode=pincode_w
    time_to_ind=int(time_w)
    # print("time_to_ind",time_to_ind)
    url = "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/{zipcode}/{date}/{date}?unitGroup=metric&include=hours&key=PQ6T4N7XPRBXVXWYJN9YZ829K&contentType=json".format(zipcode=pincode,date=date)
    try:
        if(time_to_ind>17):
            return JsonResponse({"error": "Time is not available"}, status=500)
        response = requests.get(url)
        # Check if the request was successful
        if response.status_code == 200:
            weather_data = response.json()
            timed_weather_data=weather_data.get('days', [])[0].get('hours', [])
            # timed_weather_data=weather_data.get('days', [])[0].get('hours', [])[time_to_ind]
            #dew_data = timed_weather_data
            for i in range(time_to_ind,((time_to_ind+3))):
                #print("temp ->",timed_weather_data[i].get('temp', "-999"))
                row=[timed_weather_data[i].get('temp', "-999"),timed_weather_data[i].get('humidity', "-999"),timed_weather_data[i].get('precip', "-999"),timed_weather_data[i].get('windspeed', "-999"),timed_weather_data[i].get('solarradiation', "-999")/980,timed_weather_data[i].get('solarenergy', "-999")]
                Data_Array.append(row)
                
            # print("DATA ARRAY AT ALL INDEX")
            # print(Data_Array)
            
            # Predict solidification
            for i in range(len(Data_Array)):
                del_T=predict_solidification(Data_Array[i][0], Data_Array[i][1], Data_Array[i][2], Data_Array[i][3], Data_Array[i][4], Data_Array[i][5])
                del_GD=predict_generate_and_demand(Data_Array[i][0], Data_Array[i][1], Data_Array[i][2], Data_Array[i][3], Data_Array[i][4], Data_Array[i][5])
                DeltaT_Array.append(del_T)
                GBModel_Array.append(del_GD)
                weather = WeatherV1(
                date_w=date,
                time_w=f"{time_to_ind+i:02d}:00:00",
                temperature=Data_Array[i][0],
                humidity=Data_Array[i][1],
                precipitation=Data_Array[i][2],
                windspeed=Data_Array[i][3],
                solar_rad=Data_Array[i][4],
                solar_engy=Data_Array[i][5],
                delta_t=del_T,
                place="Chandigarh",
                zipcode=str(pincode)
                )
                #removing backend storage
                weather.save()
                Sum_DeltaT+=DeltaT_Array[i]
                
            output=OutputV1(remark_text=f"Solidification depends on sum of delta T for 3 hours is {Sum_DeltaT} with input date: {date_w} time{time_w} for pincode {pincode} and input array is {Data_Array} and output array is {DeltaT_Array} ", avg_delta_t=Sum_DeltaT)
            #removing backend storage
            output.save()
            
            # print("GBMODEL ARRAY")
            # print(GBModel_Array)
            #func(GBModel_Array,Sum_DeltaT)
            #print(GBModel_Array[0][0])
            # print("DELTA T ARRAY")
            # print(DeltaT_Array)
            # print("sum is " ,Sum_DeltaT)
            # print("NEWWW GB MODEL ANSWER")
            # print(predict_generate_and_demand(Data_Array[0][0], Data_Array[0][1], Data_Array[0][2], Data_Array[0][3], Data_Array[0][4], Data_Array[0][5]))
            
            
            return JsonResponse({"formatted data":timed_weather_data})
        else:
            return JsonResponse({"error": "Failed to fetch weather data"}, status=500)
    except requests.RequestException as e:
        return JsonResponse({"error": str(e)}, status=500)

getweather/templates/getweather/_footer.html
<div class="container bg-light">
  <footer
    class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top"
  >
    <div class="col-md-4 d-flex align-items-center">
      <a href="" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
      </a>
      <span class="text-muted">&copy; 2023 LPU ; </span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3">
        <a class="text-muted" href="#"
          ><svg class="bi" width="24" height="24">
            <use xlink:href="#twitter" /></svg
        ></a>
      </li>
      <li class="ms-3">
        <a class="text-muted" href="#"
          ><svg class="bi" width="24" height="24">
            <use xlink:href="#instagram" /></svg
        ></a>
      </li>
      <li class="ms-3">
        <a class="text-muted" href="#"
          ><svg class="bi" width="24" height="24">
            <use xlink:href="#facebook" /></svg
        ></a>
      </li>
    </ul>
  </footer>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</div>

getweather/templates/getweather/_navbar.html
{% load static %}
<style>
  .bg-light {
      --bs-bg-opacity: 0.4;
      background-color: rgba(var(--bs-light-rgb), var(--bs-bg-opacity)) !important;
  }

  .navbar-custom {
      background: rgba(0, 0, 0, 0.6); /* Customize as needed */
  }

  .nav-item{
    font-size: 4vh
  }
  </style>
<nav class="navbar navbar-expand-lg navbar-light bg-light p-2 mx-3" >
  <b
    ><i>
      <a class="navbar-brand" href="{% url 'getweather:solidification' %}"></a>
        <img
          src="{% static 'getweather/logobg.png' %}"
          alt="logobg" width="250px" height="100px"
        /></a
      ></i
    ></b
  >
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNavAltMarkup"
    aria-controls="navbarNavAltMarkup"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"> </span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav mx-auto">
      <a
        class="nav-item nav-link active"
        href="{% url 'getweather:solidification' %}"
        >Home</a
      >
      <a class="nav-item nav-link" href="{% url 'getweather:anomaly' %}"
        >Anomaly Detector</a
      >
      <a class="nav-item nav-link" href="{% url 'getweather:rul' %}"
        >RUL Detector</a
      >
    </div>
  </div>
</nav>

getweather/templates/getweather/anomaly.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Anamoly Report Project X</title>
    <link rel="stylesheet" href="{% static 'getweather/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <style>
      body,
      html {
        margin: 0;
        padding: 0;
        height: 100%;
      }
      .glass-form {
        background: rgba(255, 255, 255, 0.3);
        backdrop-filter: blur(10px);
        -webkit-backdrop-filter: blur(10px);
        border: 1px solid rgba(255, 255, 255, 0.2);
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
      }

      .video-background {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        pointer-events: none; /* This ensures the video doesn't interfere with page elements */
      }

      .content {
        position: relative;
        z-index: 2; /* Ensures content is above the video */
        color: rgb(10, 10, 10); /* Adjust based on your needs */
        text-align: center;
        padding: 20px;
      }

      .content h1 {
        margin-top: 2%;
      }
    </style>
  </head>
  <body>
    <div class="video-background">
      <iframe
        width="120%"
        height="150%"
        src="https://www.youtube.com/embed/19uxBLM4pVM?autoplay=1&mute=1&loop=1&playlist=19uxBLM4pVM&controls=0&showinfo=0&autohide=1&modestbranding=1&iv_load_policy=3"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen
      ></iframe>
    </div>
    <div class="content">
      {% include 'getweather/_navbar.html' %} {% if messages %}
      <div class="msg1 container">
        <ul class="messages">
          {% for message in messages %}
          <li class="{{ message.tags }}">{{ message }}</li>
          {% endfor %}
        </ul>
      </div>
      {% endif %} {% if result %}
      <div class="ins container alert alert-info" role="alert">
        <h2>Result :</h2>
        <p>{{ result }}</p>
      </div>
      {% endif %}
      <div class="form1 container container-fluid my-auto text-center">
        <h1 class="text-center mb-4">Anomaly Detection Form</h1>

        <form
          action="{% url 'getweather:anomaly' %}"
          method="post"
          id="formSolid"
          class="p-4 shadow-lg rounded glass-form d-inline-block"
        >
          {% csrf_token %}
          <div class="form-group">
            <label for="CL_out_temp" class="h4">CL_out_temp : </label>
            <input
              type="number"
              id="CL_out_temp"
              name="CL_out_temp"
              step="any"
              class="form-control"
              required
              style="width: 100%; padding: 10px 100px"
            />

            <label for="Fluid_temp_at_3V_in" class="h4"
              >Fluid_temp_at_3V_in :
            </label>
            <input
              type="number"
              id="Fluid_temp_at_3V_in"
              name="Fluid_temp_at_3V_in"
              step="any"
              class="form-control"
              required
              style="width: 100%; padding: 10px 100px"
            />

            <label for="HT_out_fluid_temp" class="h4"
              >HT_out_fluid_temp :
            </label>
            <input
              type="number"
              step="any"
              id="HT_out_fluid_temp"
              name="HT_out_fluid_temp"
              class="form-control"
              required
              style="width: 100%; padding: 10px 100px"
            />

            <label for="HE_fluid_in_temp" class="h4">HE_fluid_in_temp : </label>
            <input
              type="number"
              step="any"
              id="HE_fluid_in_temp"
              name="HE_fluid_in_temp"
              class="form-control"
              required
              style="width: 100%; padding: 10px 100px"
            />

            <label for="HE_fluid_out_temp" class="h4"
              >HE_fluid_out_temp :
            </label>
            <input
              type="number"
              step="any"
              id="HE_fluid_out_temp"
              name="HE_fluid_out_temp"
              class="form-control"
              required
              style="width: 100%; padding: 10px 100px"
            />

            <label for="CT_in_Fluid_temp" class="h4">CT_in_Fluid_temp : </label>
            <input
              type="number"
              step="any"
              id="CT_in_Fluid_temp"
              name="CT_in_Fluid_temp"
              class="form-control"
              required
              style="width: 100%; padding: 10px 100px"
            />

            <label for="CT_out_fluid_temp" class="h4"
              >CT_out_fluid_temp :
            </label>
            <input
              type="number"
              step="any"
              id="CT_out_fluid_temp"
              name="CT_out_fluid_temp"
              class="form-control"
              required
              style="width: 100%; padding: 10px 100px"
            />

            <label for="CL_in_fluid_temp" class="h4">CL_in_fluid_temp : </label>
            <input
              type="number"
              step="any"
              id="CL_in_fluid_temp"
              name="CL_in_fluid_temp"
              class="form-control"
              required
              style="width: 100%; padding: 10px 100px"
            />
          </div>
          <button type="submit" class="btn btn-primary btn-lg btn-block mt-4">
            Submit
          </button>
        </form>
      </div>
      {%include 'getweather/_footer.html'%}
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>

    <script>
      // Function to hide messages after a few seconds
      setTimeout(function () {
        var messages = document.querySelector(".messages");
        var ins = document.querySelector(".ins");
        if (messages) {
          messages.style.display = "none";
          ins.style.display = "none";
        }
      }, 500000); // Adjust the time as needed (5000 milliseconds = 5 seconds)
    </script>
  </body>
</html>

getweather/templates/getweather/index.html
<h1>TEST PAGE</h1>

getweather/templates/getweather/rul.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>RUL Report Project X</title>
    <link rel="stylesheet" href="{% static 'getweather/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <style>
      body,
      html {
        margin: 0;
        padding: 0;
        height: 100%;
      }
      .glass-form {
        background: rgba(255, 255, 255, 0.3);
        backdrop-filter: blur(10px);
        -webkit-backdrop-filter: blur(10px);
        border: 1px solid rgba(255, 255, 255, 0.2);
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
      }

      .video-background {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        pointer-events: none; /* This ensures the video doesn't interfere with page elements */
      }

      .content {
        position: relative;
        z-index: 2; /* Ensures content is above the video */
        color: rgb(10, 10, 10); /* Adjust based on your needs */
        text-align: center;
        padding: 20px;
      }

      .content h1 {
        margin-top: 2%;
      }
    </style>
  </head>
  <body>
    <div class="video-background">
      <iframe
        width="120%"
        height="130%"
        src="https://www.youtube.com/embed/19uxBLM4pVM?autoplay=1&mute=1&loop=1&playlist=19uxBLM4pVM&controls=0&showinfo=0&autohide=1&modestbranding=1&iv_load_policy=3"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen
      ></iframe>
    </div>
    {% include 'getweather/_navbar.html' %}
    <div class="content">
      {% if messages %}
      <div class="msg1 container">
        <ul class="messages">
          {% for message in messages %}
          <li class="{{ message.tags }}">{{ message }}</li>
          {% endfor %}
        </ul>
      </div>
      {% endif %} {% if result %}
      <div class="ins container alert alert-info" role="alert">
        <h2>Remaining Usable Live :</h2>
        <p>{{ result }}</p>
      </div>
      {% endif %}
      <div class="form1 container container-fluid my-auto text-center">
        <h1 class="text-center mb-4">RUL Detection Form</h1>

        <form
          action="{% url 'getweather:rul' %}"
          method="post"
          id="formSolid"
          class="p-4 shadow-lg rounded glass-form d-inline-block"
        >
          {% csrf_token %}
          <div class="form-group">
            <label for="temperature" class="h4">Temperature : </label>
            <input
              type="number"
              step="any"
              id="temperature"
              name="temperature"
              class="form-control"
              required
              style="width: 100%; padding: 10px 100px"
            />

            <label for="pressure" class="h4">Pressure : </label>
            <input
              type="number"
              step="any"
              id="pressure"
              name="pressure"
              class="form-control"
              required
              style="width: 100%; padding: 10px 100px"
            />

            <label for="flow_rate" class="h4">Flow rate : </label>
            <input
              type="number"
              id="flow_rate"
              step="any"
              name="flow_rate"
              class="form-control"
              required
              style="width: 100%; padding: 10px 100px"
            />

            <label for="vibration" class="h4">Vibration : </label>
            <input
              type="number"
              id="vibration"
              step="any"
              name="vibration"
              class="form-control"
              required
              style="width: 100%; padding: 10px 100px"
            />

            <label for="motor_current" class="h4">Motor Current : </label>
            <input
              type="number"
              id="motor_current"
              step="any"
              name="motor_current"
              class="form-control"
              required
              style="width: 100%; padding: 10px 100px"
            />

            <label for="operating_hours" class="h4">Operating Hours : </label>
            <input
              type="number"
              id="operating_hours"
              step="any"
              name="operating_hours"
              class="form-control"
              required
              style="width: 100%; padding: 10px 100px"
            />
          </div>
          <button type="submit" class="btn btn-primary btn-lg btn-block mt-4">
            Submit
          </button>
        </form>
      </div>
      {%include 'getweather/_footer.html'%}
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <script>
      // Function to hide messages after a few seconds
      setTimeout(function () {
        var messages = document.querySelector(".messages");
        var ins = document.querySelector(".ins");
        if (messages) {
          messages.style.display = "none";
          ins.style.display = "none";
        }
      }, 50000); // Adjust the time as needed (5000 milliseconds = 5 seconds)
    </script>
  </body>
</html>

getweather/templates/getweather/solidification.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Solidification Project X</title>
    <link rel="stylesheet" href="{% static 'getweather/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <style>
      body,
      html {
        margin: 0;
        padding: 0;
        height: 100%;
        overflow: hidden;
      }
      .glass-form {
        background: rgba(255, 255, 255, 0.3);
        backdrop-filter: blur(10px);
        -webkit-backdrop-filter: blur(10px);
        border: 1px solid rgba(255, 255, 255, 0.2);
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
      }

      .video-background {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        pointer-events: none; /* This ensures the video doesn't interfere with page elements */
      }

      .content {
        position: relative;
        z-index: 2; /* Ensures content is above the video */
        color: white; /* Adjust based on your needs */
        text-align: center;
        padding: 20px;
      }

      .content h1 {
        margin-top: 20%;
      }
    </style>
  </head>
  <body>
    <div class="video-background">
      <iframe
        width="100%"
        height="100%"
        src="https://www.youtube.com/embed/19uxBLM4pVM?autoplay=1&mute=1&loop=1&playlist=19uxBLM4pVM&controls=0&showinfo=0&autohide=1&modestbranding=1&iv_load_policy=3"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen
      ></iframe>
    </div>
    {% include 'getweather/_navbar.html' %}

    <div class="content">
      <div class="msg1 my-5 container">
        {% if messages %}
        <ul class="messages">
          {% for message in messages %}
          <li class="{{ message.tags }}">{{ message }}</li>
          {% endfor %}
        </ul>
        {% endif %}
      </div>
      {% if result_dict %}
      <div class="ins my-5 container alert alert-info" role="alert">
        <h2>Possible Solutions to Prevent Solidification :</h2>
        <p>{{ result_dict.25 }}</p>
        <p>{{ result_dict.50 }}</p>
        <p>{{ result_dict.75 }}</p>
        <p>{{ result_dict.90 }}</p>
      </div>
      {% endif %}

      <div class="form1 container container-fluid my-auto mx-auto text-center">
        <h1 class="text-center mb-4">Solidifcation Detection Form</h1>
        <form
          action="{% url 'getweather:solidificationAPI' %}"
          method="post"
          id="formSolid"
          class="p-4 shadow-lg rounded glass-form d-inline-block"
          style="max-width: 600px"
        >
          {% csrf_token %}
          <div class="form-group">
            <label for="time_w" class="h4">Time (date and time): </label>
            <input
              type="datetime-local"
              id="time_w"
              name="time_w"
              class="form-control"
              required
              style="width: 100%; padding: 10px 100px"
            />
          </div>
          <button type="submit" class="btn btn-primary btn-lg btn-block mt-4">
            Submit
          </button>
        </form>
        {%include 'getweather/_footer.html'%}
      </div>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <script>
      // Function to hide messages after a few seconds
      setTimeout(function () {
        var messages = document.querySelector(".messages");
        var ins = document.querySelector(".ins");
        if (messages) {
          messages.style.display = "none";
          ins.style.display = "none";
        }
      }, 500000); // Adjust the time as needed (5000 milliseconds = 5 seconds)
    </script>
  </body>
</html>